spring:
  profiles:
    active: h2

  batch:
    job:
      names: ${custom.job.name:NONE}

  sql:
    init:
      data-locations: classpath:person.sql

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
#            StatementCreatorUtils: trace
