spring:
  batch:
    job:
      names: ${custom.job.name:NONE}
  profiles:
    active: h2
logging:
  level:
    root: info
    org:
      springframework:
        jdbc:
          core:
            JdbcTemplate: debug
            StatementCreatorUtils: trace
